### ISSUE TITLE
Instagram return empty Tables and Charts

### ISSUE THREAD

**Issue by sferez** [DavideViolante/socialblade-com-api#83]
Instagram return an empty table and value:

{ table: [], charts: [] }

**Comment by DavideViolante** [comment]
table is now returing data for Instagram, but you need to provide your cookie session from socialblade.com. See readme for more info.
charts I think is not yet returning any data and I will look into it asap.
Thank you for reporting!

**Comment by sferez** [comment]
Much appreciated thanks. It seems it is better to always pass the cookie to be sure the charts are included in the data even for YouTube and Twitter.

They also add a beta TikTok, which can be valuable if it's not a big change in the script.

**Comment by DavideViolante** [comment]
Please open a new issue about TikTok and I will look into it whenever I find some time.
I think for Twitter and Youtube the cookie is not needed because the info are publicly available on Socialblade, while Instagram data are behind Socialblade login. Anyway yes you can pass the cookie for any source without problems.
